// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(JeweryStoreDBContext))]
    [Migration("20240719011419_ProductAddNameField")]
    partial class ProductAddNameField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CategoryEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Vòng cổ"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Vòng tay"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Nhẫn"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Đồng hồ"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Bông tai"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Kiềng"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Lắc"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CounterEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Counter");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Name = "Vòng cổ Counter"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            Name = "Vòng tay Counter"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            Name = "Nhẫn Counter"
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            Name = "Đồng hồ Counter"
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            Name = "Bông tai Counter"
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            Name = "Kiềng Counter"
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            Name = "Lắc Counter"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.RoleEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Customer"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderDetailEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ProductCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CounterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PrimaryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CounterID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("UserID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = "b63d6933-e1b6-4d0e-b06e-18aca793f960",
                            CategoryID = 1,
                            Cost = 1000000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3142),
                            Description = "Vòng cổ 1",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3142),
                            Name = "Vòng cổ 1",
                            Quantity = 5,
                            Weight = 10.5f
                        },
                        new
                        {
                            ID = "d209087e-bd88-4060-81d8-ecc0b3586f5a",
                            CategoryID = 1,
                            Cost = 1500000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3155),
                            Description = "Vòng cổ 2",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3155),
                            Name = "Vòng cổ 2",
                            Quantity = 3,
                            Weight = 12f
                        },
                        new
                        {
                            ID = "f1d1f9ce-65f6-4882-ae0e-49a1f3ad5f23",
                            CategoryID = 2,
                            Cost = 500000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3164),
                            Description = "Vòng tay 1",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3164),
                            Name = "Vòng tay 1",
                            Quantity = 10,
                            Weight = 8f
                        },
                        new
                        {
                            ID = "4bab394c-75fc-418e-800f-ec736c2bee7c",
                            CategoryID = 2,
                            Cost = 700000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3171),
                            Description = "Vòng tay 2",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3171),
                            Name = "Vòng tay 2",
                            Quantity = 8,
                            Weight = 9f
                        },
                        new
                        {
                            ID = "14a6a6e0-8d0d-443b-980f-6bcca4373a46",
                            CategoryID = 3,
                            Cost = 2000000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3182),
                            Description = "Nhẫn 1",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3182),
                            Name = "Nhẫn 1",
                            Quantity = 4,
                            Weight = 5f
                        },
                        new
                        {
                            ID = "ace19bbc-9fb0-486f-97f2-a1a261b6f48e",
                            CategoryID = 3,
                            Cost = 2500000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3189),
                            Description = "Nhẫn 2",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3189),
                            Name = "Nhẫn 2",
                            Quantity = 6,
                            Weight = 6f
                        },
                        new
                        {
                            ID = "1d4c4dc5-5231-4cf2-abc2-d989c33ecf44",
                            CategoryID = 4,
                            Cost = 3000000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3196),
                            Description = "Đồng hồ 1",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3196),
                            Name = "Đồng hồ 1",
                            Quantity = 2,
                            Weight = 50f
                        },
                        new
                        {
                            ID = "968a2898-e4b5-40b5-ad63-f956eaa46138",
                            CategoryID = 4,
                            Cost = 3500000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3202),
                            Description = "Đồng hồ 2",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3202),
                            Name = "Đồng hồ 2",
                            Quantity = 3,
                            Weight = 55f
                        },
                        new
                        {
                            ID = "18bacea9-7199-4bd4-921a-35ff820637de",
                            CategoryID = 5,
                            Cost = 800000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3212),
                            Description = "Bông tai 1",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3212),
                            Name = "Bông tai 1",
                            Quantity = 12,
                            Weight = 3f
                        },
                        new
                        {
                            ID = "1d4449e2-a1f3-4fd3-a556-41cc45e81835",
                            CategoryID = 5,
                            Cost = 900000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3219),
                            Description = "Bông tai 2",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3219),
                            Name = "Bông tai 2",
                            Quantity = 14,
                            Weight = 3.5f
                        },
                        new
                        {
                            ID = "6294cc35-a47c-484c-a140-66924d909453",
                            CategoryID = 6,
                            Cost = 1200000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3226),
                            Description = "Kiềng 1",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3226),
                            Name = "Kiềng 1",
                            Quantity = 7,
                            Weight = 20f
                        },
                        new
                        {
                            ID = "4fd0f1d2-eef7-438a-8798-77b905b65700",
                            CategoryID = 6,
                            Cost = 1400000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3232),
                            Description = "Kiềng 2",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3232),
                            Name = "Kiềng 2",
                            Quantity = 6,
                            Weight = 22f
                        },
                        new
                        {
                            ID = "daa86e6a-0db1-4f5d-84d5-a669bebcdb28",
                            CategoryID = 7,
                            Cost = 1000000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3241),
                            Description = "Lắc 1",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3241),
                            Name = "Lắc 1",
                            Quantity = 9,
                            Weight = 15f
                        },
                        new
                        {
                            ID = "ec5b6d08-7750-4501-8207-2fc356840b17",
                            CategoryID = 7,
                            Cost = 1100000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3247),
                            Description = "Lắc 2",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3247),
                            Name = "Lắc 2",
                            Quantity = 8,
                            Weight = 16.5f
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ConditionsOfUse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumReduce")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("ReducedPercent")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Promotion");

                    b.HasData(
                        new
                        {
                            ID = "9084f86f-7468-40d3-a453-8142ace6e2e4",
                            ConditionsOfUse = 5000000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3325),
                            Description = "Summer Sale",
                            ExpiresTime = new DateTime(2024, 8, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3333),
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3325),
                            MaximumReduce = 500000m,
                            ReducedPercent = 10f,
                            Status = "Active"
                        },
                        new
                        {
                            ID = "6b797d2e-b9ce-4932-913c-ac5d7f02ae55",
                            ConditionsOfUse = 3000000m,
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3350),
                            Description = "Winter Sale",
                            ExpiresTime = new DateTime(2024, 9, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3358),
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(3350),
                            MaximumReduce = 300000m,
                            ReducedPercent = 15f,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = "a8da35fb-d36c-4f6c-abe9-3aeaa4781b80",
                            Address = "123 Admin St.",
                            CreatedAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(2780),
                            Email = "admin@gmail.com",
                            FullName = "Administrator",
                            LastestUpdateAt = new DateTime(2024, 7, 19, 8, 14, 18, 598, DateTimeKind.Local).AddTicks(2729),
                            PasswordHash = "$2b$12$HE0v7UbzZwl6wY3y/jXhR.oYyGo2DWcIRFQatHueQLw4aS1PbeI8y",
                            PhoneNumber = "1234567890",
                            RoleID = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CounterEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderDetailEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.OrderEntity", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjecs.Models.ProductEntity", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.CounterEntity", "Counter")
                        .WithMany("Orders")
                        .HasForeignKey("CounterID");

                    b.HasOne("BusinessObjecs.Models.PromotionEntity", "Promotion")
                        .WithMany("Orders")
                        .HasForeignKey("PromotionID");

                    b.HasOne("BusinessObjecs.Models.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.UserEntity", "User")
                        .WithMany("Promotions")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CounterEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
