// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(JeweryStoreDBContext))]
    [Migration("20240717084802_tên migration")]
    partial class tênmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CategoryEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Vòng cổ"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Vòng tay"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Nhẫn"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Đồng hồ"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Bông tai"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Kiềng"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Lắc"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CounterEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Counter");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CategoryID = 1,
                            Name = "Vòng cổ Counter"
                        },
                        new
                        {
                            ID = 2,
                            CategoryID = 2,
                            Name = "Vòng tay Counter"
                        },
                        new
                        {
                            ID = 3,
                            CategoryID = 3,
                            Name = "Nhẫn Counter"
                        },
                        new
                        {
                            ID = 4,
                            CategoryID = 4,
                            Name = "Đồng hồ Counter"
                        },
                        new
                        {
                            ID = 5,
                            CategoryID = 5,
                            Name = "Bông tai Counter"
                        },
                        new
                        {
                            ID = 6,
                            CategoryID = 6,
                            Name = "Kiềng Counter"
                        },
                        new
                        {
                            ID = 7,
                            CategoryID = 7,
                            Name = "Lắc Counter"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.RoleEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Customer"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderDetailEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ProductCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CounterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("CounterID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("UserID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = "80c2b05d-9930-4270-9ed4-6e44533f32dc",
                            CategoryID = 1,
                            Cost = 1000000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5804),
                            Description = "Vòng cổ 1",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5804),
                            Quantity = 5,
                            Weight = 10.5f
                        },
                        new
                        {
                            ID = "a4b87b58-948e-4b9d-82aa-eafd6f520751",
                            CategoryID = 1,
                            Cost = 1500000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5818),
                            Description = "Vòng cổ 2",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5818),
                            Quantity = 3,
                            Weight = 12f
                        },
                        new
                        {
                            ID = "d47cf759-d436-40c5-8743-3c4ff2dfa59e",
                            CategoryID = 2,
                            Cost = 500000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5825),
                            Description = "Vòng tay 1",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5825),
                            Quantity = 10,
                            Weight = 8f
                        },
                        new
                        {
                            ID = "c6f39d5a-ef8d-4378-a5ae-9996cdaf3936",
                            CategoryID = 2,
                            Cost = 700000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5845),
                            Description = "Vòng tay 2",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5845),
                            Quantity = 8,
                            Weight = 9f
                        },
                        new
                        {
                            ID = "51c57838-d670-43a8-a507-51d85755ada1",
                            CategoryID = 3,
                            Cost = 2000000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5852),
                            Description = "Nhẫn 1",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5852),
                            Quantity = 4,
                            Weight = 5f
                        },
                        new
                        {
                            ID = "4038100e-8758-488f-ab1e-3dd5201c7f81",
                            CategoryID = 3,
                            Cost = 2500000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5860),
                            Description = "Nhẫn 2",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5860),
                            Quantity = 6,
                            Weight = 6f
                        },
                        new
                        {
                            ID = "ed7911ba-ed22-4d81-a3c7-ef7658332b63",
                            CategoryID = 4,
                            Cost = 3000000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5867),
                            Description = "Đồng hồ 1",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5867),
                            Quantity = 2,
                            Weight = 50f
                        },
                        new
                        {
                            ID = "0500a3f5-9816-418d-b11a-2aa4ef391a4e",
                            CategoryID = 4,
                            Cost = 3500000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5875),
                            Description = "Đồng hồ 2",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5875),
                            Quantity = 3,
                            Weight = 55f
                        },
                        new
                        {
                            ID = "0ea0a181-a50b-4157-b499-17e42b0efbfe",
                            CategoryID = 5,
                            Cost = 800000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5882),
                            Description = "Bông tai 1",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5882),
                            Quantity = 12,
                            Weight = 3f
                        },
                        new
                        {
                            ID = "93de1d5c-ae63-41bc-b8b9-f239f8a6e120",
                            CategoryID = 5,
                            Cost = 900000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5890),
                            Description = "Bông tai 2",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5890),
                            Quantity = 14,
                            Weight = 3.5f
                        },
                        new
                        {
                            ID = "0632586e-f9ec-4d9c-8e28-3e67ef2b551c",
                            CategoryID = 6,
                            Cost = 1200000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5896),
                            Description = "Kiềng 1",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5896),
                            Quantity = 7,
                            Weight = 20f
                        },
                        new
                        {
                            ID = "7a443370-4562-4afe-ae84-1c765f7e9108",
                            CategoryID = 6,
                            Cost = 1400000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5904),
                            Description = "Kiềng 2",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5904),
                            Quantity = 6,
                            Weight = 22f
                        },
                        new
                        {
                            ID = "b8b5c091-4229-4484-9348-f961a379dc3b",
                            CategoryID = 7,
                            Cost = 1000000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5911),
                            Description = "Lắc 1",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5911),
                            Quantity = 9,
                            Weight = 15f
                        },
                        new
                        {
                            ID = "3e4f1126-79ef-47cc-975a-be0ce3388bd8",
                            CategoryID = 7,
                            Cost = 1100000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5918),
                            Description = "Lắc 2",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5918),
                            Quantity = 8,
                            Weight = 16.5f
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ConditionsOfUse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExchangePoint")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpiresTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumReduce")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("ReducedPercent")
                        .HasColumnType("real");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Promotion");

                    b.HasData(
                        new
                        {
                            ID = "ca577c12-932b-4c49-8d12-90d22cf67b94",
                            ConditionsOfUse = 5000000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5949),
                            Description = "Summer Sale",
                            ExchangePoint = 100,
                            ExpiresTime = new DateTime(2024, 8, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5955),
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5949),
                            MaximumReduce = 500000m,
                            ReducedPercent = 10f
                        },
                        new
                        {
                            ID = "3cf14a06-24f2-4fd0-8c7d-2c5214712b47",
                            ConditionsOfUse = 3000000m,
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5968),
                            Description = "Winter Sale",
                            ExchangePoint = 50,
                            ExpiresTime = new DateTime(2024, 9, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5973),
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5968),
                            MaximumReduce = 300000m,
                            ReducedPercent = 15f
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = "a7e19803-eee7-4d48-a73e-193fde213aaf",
                            Address = "123 Admin St.",
                            CreatedAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5684),
                            Email = "admin@gmail.com",
                            FullName = "Administrator",
                            LastestUpdateAt = new DateTime(2024, 7, 17, 15, 48, 1, 65, DateTimeKind.Local).AddTicks(5660),
                            PasswordHash = "$2b$12$HE0v7UbzZwl6wY3y/jXhR.oYyGo2DWcIRFQatHueQLw4aS1PbeI8y",
                            PhoneNumber = "1234567890",
                            Point = 0,
                            RoleID = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CounterEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.CategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderDetailEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.OrderEntity", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjecs.Models.ProductEntity", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.CounterEntity", "Counter")
                        .WithMany("Orders")
                        .HasForeignKey("CounterID");

                    b.HasOne("BusinessObjecs.Models.PromotionEntity", "Promotion")
                        .WithMany("Orders")
                        .HasForeignKey("PromotionID");

                    b.HasOne("BusinessObjecs.Models.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Counter");

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.UserEntity", "User")
                        .WithMany("Promotions")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CounterEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
