// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(JeweryStoreDBContext))]
    [Migration("20240722051431_AddImgUrlToProductEntity")]
    partial class AddImgUrlToProductEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CategoryEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Vòng cổ"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Vòng tay"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Nhẫn"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Đồng hồ"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Bông tai"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Kiềng"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Lắc"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.RoleEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Customer"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Manager"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderDetailEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ProductCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductID");

                    b.ToTable("OrderDetail");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PrimaryPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("PromotionID");

                    b.HasIndex("UserID");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("ID");

                    b.HasIndex("CategoryID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = "b40d2785-7a4b-486a-8ca8-d2cc9fc31adb",
                            CategoryID = 1,
                            Cost = 1000000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1606),
                            Description = "Vòng cổ 1",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1606),
                            Name = "Vòng cổ 1",
                            Quantity = 5,
                            Weight = 10.5f
                        },
                        new
                        {
                            ID = "903b8e9c-13c3-462a-8096-25a37f8b0559",
                            CategoryID = 1,
                            Cost = 1500000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1620),
                            Description = "Vòng cổ 2",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1620),
                            Name = "Vòng cổ 2",
                            Quantity = 3,
                            Weight = 12f
                        },
                        new
                        {
                            ID = "d3339339-da79-4a94-84fa-0f3cfe91e728",
                            CategoryID = 2,
                            Cost = 500000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1628),
                            Description = "Vòng tay 1",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1628),
                            Name = "Vòng tay 1",
                            Quantity = 10,
                            Weight = 8f
                        },
                        new
                        {
                            ID = "83fbab8f-1c70-4728-bc01-721f2fda9d1e",
                            CategoryID = 2,
                            Cost = 700000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1677),
                            Description = "Vòng tay 2",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1677),
                            Name = "Vòng tay 2",
                            Quantity = 8,
                            Weight = 9f
                        },
                        new
                        {
                            ID = "1bf33110-0316-4c69-afb9-cf7a3d062f7b",
                            CategoryID = 3,
                            Cost = 2000000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1687),
                            Description = "Nhẫn 1",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1687),
                            Name = "Nhẫn 1",
                            Quantity = 4,
                            Weight = 5f
                        },
                        new
                        {
                            ID = "75bb724a-7d7b-44bb-becc-4209c94cf622",
                            CategoryID = 3,
                            Cost = 2500000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1696),
                            Description = "Nhẫn 2",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1696),
                            Name = "Nhẫn 2",
                            Quantity = 6,
                            Weight = 6f
                        },
                        new
                        {
                            ID = "930d9ab2-566d-491f-b16a-a5f5325bf5ec",
                            CategoryID = 4,
                            Cost = 3000000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1704),
                            Description = "Đồng hồ 1",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1704),
                            Name = "Đồng hồ 1",
                            Quantity = 2,
                            Weight = 50f
                        },
                        new
                        {
                            ID = "64bb6878-76b9-4a22-bc1b-faa45c7f0d20",
                            CategoryID = 4,
                            Cost = 3500000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1711),
                            Description = "Đồng hồ 2",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1711),
                            Name = "Đồng hồ 2",
                            Quantity = 3,
                            Weight = 55f
                        },
                        new
                        {
                            ID = "abde158b-7696-4de5-be79-81bd1d9b5d63",
                            CategoryID = 5,
                            Cost = 800000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1720),
                            Description = "Bông tai 1",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1720),
                            Name = "Bông tai 1",
                            Quantity = 12,
                            Weight = 3f
                        },
                        new
                        {
                            ID = "122858cb-f253-494b-915d-71b1dc8676ed",
                            CategoryID = 5,
                            Cost = 900000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1727),
                            Description = "Bông tai 2",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1727),
                            Name = "Bông tai 2",
                            Quantity = 14,
                            Weight = 3.5f
                        },
                        new
                        {
                            ID = "9f201f61-1e2a-4dcf-9624-f01f86e3a3e9",
                            CategoryID = 6,
                            Cost = 1200000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1735),
                            Description = "Kiềng 1",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1735),
                            Name = "Kiềng 1",
                            Quantity = 7,
                            Weight = 20f
                        },
                        new
                        {
                            ID = "309e68e9-b1b7-400d-838a-04c9fb5c7038",
                            CategoryID = 6,
                            Cost = 1400000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1742),
                            Description = "Kiềng 2",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1742),
                            Name = "Kiềng 2",
                            Quantity = 6,
                            Weight = 22f
                        },
                        new
                        {
                            ID = "3d73ae7e-f3ee-43fe-92ca-4a3252f9aacd",
                            CategoryID = 7,
                            Cost = 1000000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1751),
                            Description = "Lắc 1",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1751),
                            Name = "Lắc 1",
                            Quantity = 9,
                            Weight = 15f
                        },
                        new
                        {
                            ID = "ce95357a-9a62-4f88-bdc1-864a9dcf3d1a",
                            CategoryID = 7,
                            Cost = 1100000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1758),
                            Description = "Lắc 2",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1758),
                            Name = "Lắc 2",
                            Quantity = 8,
                            Weight = 16.5f
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ConditionsOfUse")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpiresTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaximumReduce")
                        .HasColumnType("decimal(18,2)");

                    b.Property<float>("ReducedPercent")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Promotion");

                    b.HasData(
                        new
                        {
                            ID = "5a14ff3b-092f-4215-87f2-c776128a4a6d",
                            ConditionsOfUse = 5000000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1791),
                            Description = "Summer Sale",
                            ExpiresTime = new DateTime(2024, 8, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1796),
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1791),
                            MaximumReduce = 500000m,
                            ReducedPercent = 10f,
                            Status = "Active"
                        },
                        new
                        {
                            ID = "679edb57-c064-405a-81a5-1fa324cf2a39",
                            ConditionsOfUse = 3000000m,
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1809),
                            Description = "Winter Sale",
                            ExpiresTime = new DateTime(2024, 9, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1815),
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1809),
                            MaximumReduce = 300000m,
                            ReducedPercent = 15f,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeleterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastestUpdateAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UpdaterID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("RoleID");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            ID = "40759165-aee9-43b2-8342-8402542f4b8f",
                            Address = "123 Admin St.",
                            CreatedAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1563),
                            Email = "admin@gmail.com",
                            FullName = "Administrator",
                            LastestUpdateAt = new DateTime(2024, 7, 22, 12, 14, 29, 481, DateTimeKind.Local).AddTicks(1519),
                            PasswordHash = "$2b$12$HE0v7UbzZwl6wY3y/jXhR.oYyGo2DWcIRFQatHueQLw4aS1PbeI8y",
                            PhoneNumber = "1234567890",
                            RoleID = 1,
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderDetailEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.OrderEntity", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObjecs.Models.ProductEntity", "Product")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.PromotionEntity", "Promotion")
                        .WithMany("Orders")
                        .HasForeignKey("PromotionID");

                    b.HasOne("BusinessObjecs.Models.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.CategoryEntity", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.UserEntity", "User")
                        .WithMany("Promotions")
                        .HasForeignKey("UserID");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.HasOne("BusinessObjecs.Models.Configured.RoleEntity", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.CategoryEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("BusinessObjecs.Models.Configured.RoleEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BusinessObjecs.Models.OrderEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObjecs.Models.ProductEntity", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("BusinessObjecs.Models.PromotionEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("BusinessObjecs.Models.UserEntity", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
